### ISSUE TITLE
whoami command broken

### ISSUE THREAD

**Issue by rpwagner** [globusonline/pilot1-tools#31]
```
(base) Magik:~ rpwagner$ pilot whoami
Traceback (most recent call last):
  File "/Users/rpwagner/anaconda3/bin/pilot", line 10, in <module>
    sys.exit(cli())
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/commands/auth/auth_commands.py", line 65, in whoami
    info = config.get_user_info()
AttributeError: 'Config' object has no attribute 'get_user_info'
```

**Comment by NickolausDS** [comment]
Fixed
