### ISSUE TITLE
login triggers error on local_endpoint

### ISSUE THREAD

**Issue by rpwagner** [globusonline/pilot1-tools#51]
Login goes fine, but then attribute needs to be set.

I had deleted the config file and GCP was not running. Error also happens when GCP is running.

Logging in when the config file is in place with the local endpoint is configured does not cause the error.

```
(base) Magik:~ rpwagner$ pilot login
You have been logged in.
Traceback (most recent call last):
  File "/Users/rpwagner/anaconda3/bin/pilot", line 10, in <module>
    sys.exit(cli())
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/commands/auth/auth_commands.py", line 44, in login
    globus_sdk.LocalGlobusConnectPersonal().endpoint_id
AttributeError: can't set attribute
(base) Magik:~ rpwagner$ 
```

**Comment by NickolausDS** [comment]
Fixed
