### ISSUE TITLE
project delete requires a project to be set

### ISSUE THREAD

**Issue by rpwagner** [globusonline/pilot1-tools#53]
Doesn't have to be the project being deleted.

```
(base) Magik:type-class rpwagner$ pilot project delete pilot-tutorial-2
Traceback (most recent call last):
  File "/Users/rpwagner/anaconda3/bin/pilot", line 10, in <module>
    sys.exit(cli())
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/commands/project/project.py", line 194, in delete
    results = search.search_commands.search_by_project(project=project)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/commands/search/search_commands.py", line 35, in search_by_project
    return sc.post_search(pc.get_index(), search_data).data
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/client.py", line 82, in get_index
    return self.project.get_info(project)['search_index']
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/project.py", line 88, in get_info
    raise PilotInvalidProject(f'No project exists {project}')
pilot.exc.PilotInvalidProject: No project exists None
(base) Magik:type-class rpwagner$ pilot project set ncipilot1
Current project set to ncipilot1
(base) Magik:type-class rpwagner$ pilot project delete pilot-tutorial-2

////////////////////////////////////////////////////////////////////////////////
DANGER ZONE
////////////////////////////////////////////////////////////////////////////////
This will delete all data and search results in yourproject.
0 datasets will be deleted for pilot-tutorial-2
////////////////////////////////////////////////////////////////////////////////
DANGER ZONE
////////////////////////////////////////////////////////////////////////////////
Please type the name (pilot-tutorial-2) of your project to delete it> pilot-tutorial-2
Deleting Data...
Deleting Search Records...
Removing project...
Project pilot-tutorial-2 has been deleted successfully.
(base) Magik:type-class rpwagner$ 
```

**Comment by NickolausDS** [comment]
Ahh, this is a regression. At some point I have fixed this bug before. Good find!

**Comment by NickolausDS** [comment]
Fixed
