### ISSUE TITLE
pilot upload needs to handle arbitrary file types

### ISSUE THREAD

**Issue by rpwagner** [globusonline/pilot1-tools#55]
We can't assume they're TSV. Need to try extracting column metadata then try a different way, then go for minimal file metadata.

```
pilot upload GDC_metadata.txt /
Traceback (most recent call last):
  File "/Users/rpwagner/anaconda3/bin/pilot", line 10, in <module>
    sys.exit(cli())
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/commands/transfer/transfer_commands.py", line 81, in upload
    skip_analysis=no_analyze)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/search.py", line 122, in scrape_metadata
    skip_analysis=skip_analysis),
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/search.py", line 285, in gen_remote_file_manifest
    metadata = analyze_dataframe(filepath, fkeys) if not skip_analysis else {}
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/analysis.py", line 71, in analyze_dataframe
    ts_info = tableschema.Schema(tableschema.infer(filename)).descriptor
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/tableschema/infer.py", line 25, in infer
    descriptor = table.infer(limit=limit, confidence=confidence)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/tableschema/table.py", line 148, in infer
    with self.__stream as stream:
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/tabulator/stream.py", line 162, in __enter__
    self.open()
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/tabulator/stream.py", line 250, in open
    raise exceptions.FormatError(message)
tabulator.exceptions.FormatError: Format "txt" is not supported
```

**Comment by NickolausDS** [comment]
I'll test this on a list of different files: 

* [ ] PDF
* [ ] PNG
* [ ] CSV
* [ ] TSV
* [ ] plain text

Choosing whether to analyze them seems pretty straightforward. It seems like the next big expectation would be seeing previews in the portal. For example if a user uploads an image, they'd want to see that show up. Currently, the detail page for NCI Pilot doesn't switch between different types, it only expects text/TSVs.

**Comment by rpwagner** [comment]
Having it recognize the file and do sensible things for preview based on mime type is useful. Do what you can simplify using common Python packages for now, like getting image metadata (pixels, color, etc.). We can get more detailed later. Worst case, just get the basic file stats like the size and checksum.

**Comment by NickolausDS** [comment]
It currently adds the very basics (size and checksum), but doesn't do anything specific for anything other than tsvs and csvs. I'll keep the issue open to add more after I get preview working on the portal.

**Comment by NickolausDS** [comment]
Done
